# serverless.yml

service: WeatherAPIServerless

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1

functions:
  app:
    handler: app.js
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'